run:
  timeout: 10m
  modules-download-mode: readonly
  tests: false

linters:
  # Disable all linters.
  # Default: false
  disable-all: true
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
    # standard library linter and formatter.
    - goimports 
    # checks whether HTTP response body is closed successfully
    - bodyclose
    # Go linter that checks if package imports are in a list of acceptable packages
    - depguard
    - errcheck
    - goconst
    # Inspects source code for security problems
    - gosec
    - gosimple
    - govet
    # Finds commonly misspelled English words in comments
    - misspell
    # Finds naked returns in functions greater than a specified function length
    - nakedret
    - staticcheck
    - stylecheck
    - typecheck
    # Remove unnecessary type conversions
    - unconvert
    - unused

linters-settings:
  goconst:
    min-len: 5
    min-occurences: 5
  
  govet:
    check-shadowing: true
    
  nakedret:
    max-func-lines: 0

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0